version: "1.0"
info:
  model: int-scaffold
services:
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.451
- serviceName: edge.newpkg16_08.integrations:getDate
  packages:
  - name: EdgeNewPkg16_08
    version: "1.0"
- serviceName: edge.newpkg16_08.integrations:testHTTP
  packages:
  - name: EdgeNewPkg16_08
    version: "1.0"
packages:
- name: EdgeNewPkg16_08
  gitServerName: testServer1
  gitUrl: https://github.com/PoojaAnandGit/EdgeNewPkg16_08
  gitUsername: PoojaAnandGit
  gitToken: edge.scaffolding.EdgeNewPkg16_08.testServer1.gitToken
  gitBranch: main
